"""empty message

Revision ID: 9e3920bcafe1
Revises: 
Create Date: 2020-03-22 19:45:53.374428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3920bcafe1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LinRegResults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('YearsExperience', sa.Float(), nullable=True),
    sa.Column('Prediction', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Test_SES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prenom', sa.String(length=200), nullable=True),
    sa.Column('nom', sa.String(length=200), nullable=True),
    sa.Column('groupe', sa.String(length=200), nullable=True),
    sa.Column('exercice', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('answer', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Test_SES')
    op.drop_table('LinRegResults')
    # ### end Alembic commands ###
